"""Core package initialization"""
from app.core.logging import logger
from app.core.exceptions import (
    RAGBaseException,
    DocumentProcessingError,
    EmptyDocumentError,
    CorruptedDocumentError,
    UnsupportedDocumentError,
    ChunkingError,
    EmptyTextError,
    EmbeddingError,
    EmbeddingModelError,
    VectorStoreError,
    DatabaseConnectionError,
    DatabaseQueryError,
    LLMProviderError,
    LLMConnectionError,
    LLMRateLimitError,
    LLMAuthenticationError,
    LLMResponseError,
    ValidationError,
    EmptyQueryError,
    QueryTooLongError,
    RetrievalError,
    NoDocumentsFoundError,
)

__all__ = [
    "logger",
    "RAGBaseException",
    "DocumentProcessingError",
    "EmptyDocumentError",
    "CorruptedDocumentError",
    "UnsupportedDocumentError",
    "ChunkingError",
    "EmptyTextError",
    "EmbeddingError",
    "EmbeddingModelError",
    "VectorStoreError",
    "DatabaseConnectionError",
    "DatabaseQueryError",
    "LLMProviderError",
    "LLMConnectionError",
    "LLMRateLimitError",
    "LLMAuthenticationError",
    "LLMResponseError",
    "ValidationError",
    "EmptyQueryError",
    "QueryTooLongError",
    "RetrievalError",
    "NoDocumentsFoundError",
]
